/**
 * Qwen CosyVoice 模型类型
 */
export type QwenTTSModel =
  | 'cosyvoice-v1'
  | 'cosyvoice-v2'
  | 'cosyvoice-v3-flash'
  | 'cosyvoice-v3-plus';

/**
 * cosyvoice-v1 支持的音色
 *
 * 注意：v1 不支持方言
 */
export type CosyVoiceV1Voice =
  | 'longwan'
  | 'longcheng'
  | 'longhua'
  | 'longxiaochun'
  | 'longxiaoxia'
  | 'longxiaocheng'
  | 'longxiaobai'
  | 'longlaotie'
  | 'longshu'
  | 'longshuo'
  | 'longjing'
  | 'longmiao'
  | 'longyue'
  | 'longyuan'
  | 'longfei'
  | 'longjielidou'
  | 'longtong'
  | 'longxiang'
  | 'loongstella'
  | 'loongbella';

/**
 * cosyvoice-v2 支持的音色
 */
export type CosyVoiceV2Voice =
  | 'longyingxiao'
  | 'longjiqi'
  | 'longhouge'
  | 'longjixin'
  | 'longanyue'
  | 'longshange'
  | 'longanmin'
  | 'longdaiyu'
  | 'longgaoseng'
  | 'longanli'
  | 'longanlang'
  | 'longanwen'
  | 'longanyun'
  | 'longyumi_v2'
  | 'longxiaochun_v2'
  | 'longxiaoxia_v2'
  | 'longyichen'
  | 'longwanjun'
  | 'longlaobo'
  | 'longlaoyi'
  | 'longbaizhi'
  | 'longsanshu'
  | 'longxiu_v2'
  | 'longmiao_v2'
  | 'longyue_v2'
  | 'longnan_v2'
  | 'longyuan_v2'
  | 'longanqin'
  | 'longanya'
  | 'longanshuo'
  | 'longanling'
  | 'longanzhi'
  | 'longanrou'
  | 'longqiang_v2'
  | 'longhan_v2'
  | 'longxing_v2'
  | 'longhua_v2'
  | 'longwan_v2'
  | 'longcheng_v2'
  | 'longfeifei_v2'
  | 'longxiaocheng_v2'
  | 'longzhe_v2'
  | 'longyan_v2'
  | 'longtian_v2'
  | 'longze_v2'
  | 'longshao_v2'
  | 'longhao_v2'
  | 'kabuleshen_v2'
  | 'longhuhu'
  | 'longanpei'
  | 'longwangwang'
  | 'longpaopao'
  | 'longshanshan'
  | 'longniuniu'
  | 'longyingmu'
  | 'longyingxun'
  | 'longyingcui'
  | 'longyingda'
  | 'longyingjing'
  | 'longyingyan'
  | 'longyingtian'
  | 'longyingbing'
  | 'longyingtao'
  | 'longyingling'
  | 'longanran'
  | 'longanxuan'
  | 'longanchong'
  | 'longanping'
  | 'longjielidou_v2'
  | 'longling_v2'
  | 'longke_v2'
  | 'longxian_v2'
  | 'longlaotie_v2'
  | 'longjiayi_v2'
  | 'longtao_v2'
  | 'longfei_v2'
  | 'libai_v2'
  | 'longjin_v2'
  | 'longshu_v2'
  | 'loongbella_v2'
  | 'longshuo_v2'
  | 'longxiaobai_v2'
  | 'longjing_v2'
  | 'loongstella_v2'
  | 'loongyuuna_v2'
  | 'loongyuuma_v2'
  | 'loongjihun_v2'
  | 'loongeva_v2'
  | 'loongbrian_v2'
  | 'loongluna_v2'
  | 'loongluca_v2'
  | 'loongemily_v2'
  | 'loongeric_v2'
  | 'loongabby_v2'
  | 'loongannie_v2'
  | 'loongandy_v2'
  | 'loongava_v2'
  | 'loongbeth_v2'
  | 'loongbetty_v2'
  | 'loongcindy_v2'
  | 'loongcally_v2'
  | 'loongdavid_v2'
  | 'loongdonna_v2'
  | 'loongkyong_v2'
  | 'loongtomoka_v2'
  | 'loongtomoya_v2';

/**
 * cosyvoice-v3-flash 支持的音色
 */
export type CosyVoiceV3FlashVoice =
  | 'longanyang'
  | 'longanhuan'
  | 'longhuhu_v3'
  | 'longpaopao_v3'
  | 'longjielidou_v3'
  | 'longxian_v3'
  | 'longling_v3'
  | 'longshanshan_v3'
  | 'longniuniu_v3'
  | 'longjiaxin_v3'
  | 'longjiayi_v3'
  | 'longanyue_v3'
  | 'longlaotie_v3'
  | 'longshange_v3'
  | 'longanmin_v3'
  | 'loongkyong_v3'
  | 'loongriko_v3'
  | 'loongtomoka_v3'
  | 'longfei_v3'
  | 'longyingxiao_v3'
  | 'longyingxun_v3'
  | 'longyingjing_v3'
  | 'longyingling_v3'
  | 'longyingtao_v3'
  | 'longxiaochun_v3'
  | 'longxiaoxia_v3'
  | 'longyumi_v3'
  | 'longanyun_v3'
  | 'longanwen_v3'
  | 'longanli_v3'
  | 'longanlang_v3'
  | 'longyingmu_v3'
  | 'longantai_v3'
  | 'longhua_v3'
  | 'longcheng_v3'
  | 'longze_v3'
  | 'longzhe_v3'
  | 'longyan_v3'
  | 'longxing_v3'
  | 'longtian_v3'
  | 'longwan_v3'
  | 'longqiang_v3'
  | 'longfeifei_v3'
  | 'longhao_v3'
  | 'longanrou_v3'
  | 'longhan_v3'
  | 'longanzhi_v3'
  | 'longanling_v3'
  | 'longanya_v3'
  | 'longanqin_v3'
  | 'longmiao_v3'
  | 'longsanshu_v3'
  | 'longyuan_v3'
  | 'longyue_v3'
  | 'longxiu_v3'
  | 'longnan_v3'
  | 'longwanjun_v3'
  | 'longyichen_v3'
  | 'longlaobo_v3'
  | 'longlaoyi_v3'
  | 'longjiqi_v3'
  | 'longhouge_v3'
  | 'longdaiyu_v3'
  | 'longanran_v3'
  | 'longanxuan_v3'
  | 'longshuo_v3'
  | 'longshu_v3'
  | 'loongbella_v3';

/**
 * cosyvoice-v3-plus 支持的音色
 */
export type CosyVoiceV3PlusVoice = 'longanyang' | 'longanhuan';

/**
 * Qwen CosyVoice 全部音色（所有模型合集）
 */
export type CosyVoiceVoice =
  | CosyVoiceV1Voice
  | CosyVoiceV2Voice
  | CosyVoiceV3FlashVoice
  | CosyVoiceV3PlusVoice;

/**
 * Qwen Realtime TTS 支持的音色
 *
 * 来源: https://help.aliyun.com/zh/model-studio/qwen-tts-realtime
 */
export type QwenRealtimeVoice =
  | 'Cherry'
  | 'Serena'
  | 'Ethan'
  | 'Chelsie'
  | 'Momo'
  | 'Vivian'
  | 'Moon'
  | 'Maia'
  | 'Kai'
  | 'Nofish'
  | 'Bella'
  | 'Jennifer'
  | 'Ryan'
  | 'Katerina'
  | 'Aiden'
  | 'Eldric Sage'
  | 'Mia'
  | 'Mochi'
  | 'Bellona'
  | 'Vincent'
  | 'Bunny'
  | 'Neil'
  | 'Elias'
  | 'Arthur'
  | 'Nini'
  | 'Seren'
  | 'Pip'
  | 'Stella'
  | 'Bodega'
  | 'Sonrisa'
  | 'Alek'
  | 'Dolce'
  | 'Sohee'
  | 'Ono Anna'
  | 'Lenn'
  | 'Emilien'
  | 'Andre'
  | 'Radio Gol'
  | 'Jada'
  | 'Dylan'
  | 'Li'
  | 'Marcus'
  | 'Roy'
  | 'Peter'
  | 'Sunny'
  | 'Eric'
  | 'Rocky'
  | 'Kiki';
