export type { CollectOptions } from '@/tts/utils/collect';
export { collectAudio } from '@/tts/utils/collect';
export type { PcmToOpusOptions } from '@/tts/utils/pcm-to-opus';
export { pcmToOpus } from '@/tts/utils/pcm-to-opus';
export type { PlayOptions } from '@/tts/utils/play';
export { playAudio } from '@/tts/utils/play';
export type { SaveOptions } from '@/tts/utils/save';
export { saveTTSResponse } from '@/tts/utils/save';
export { saveAudio } from '@/tts/utils/save-audio';
export type { TeeOptions } from '@/tts/utils/tee';
export { teeAudio } from '@/tts/utils/tee';
